debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.SimpleBBS: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/XE
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:h2:tcp://localhost/~/board
    username: board_project
    password: board_project
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql.init.mode: always

---

spring:
  config:
    activate:
      on-profile: testdb

